import re

file_path = r"c:\Users\Admin\Desktop\fyp\upNext\src\contexts\EventStore.tsx"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# 1. Additional 23 Events
extra_events = '''  {
    id: 'evt-113',
    ownerId: 'user-organizer-13',
    title: 'KNUST Tech Innovators Demo Day 2026',
    description: 'Student engineering teams and tech startups from KNUST present hardware prototypes, IoT devices, and web applications to industry judges.',
    category: 'Technology',
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-10-22T09:00:00.000Z',
    endAt: '2026-10-22T17:00:00.000Z',
    venue: 'Great Hall Auditorium, KNUST',
    address: 'KNUST Campus',
    city: 'Kumasi',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'KNUST Innovation Hub',
      logo: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=200&auto=format&fit=crop&q=80',
      bio: 'Fostering engineering innovation, robotics labs, and student ventures in Kumasi.',
      type: 'Institution',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'evt-114',
    ownerId: 'user-organizer-14',
    title: 'Chale Wote Street Art & Mural Festival',
    description: 'An open-air festival bringing together street painters, graffiti artists, performance art, drumming circles, and indie music.',
    category: 'Arts & Culture',
    coverImage: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-10-25T11:00:00.000Z',
    endAt: '2026-10-26T22:00:00.000Z',
    venue: 'Jamestown High Street',
    address: 'Ussher Fort Promenade',
    city: 'Accra',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'ACCRA [ALT] Radio & Culture',
      logo: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=200&auto=format&fit=crop&q=80',
      bio: 'Independent art collective and producers of Chale Wote Street Art Festival.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'evt-115',
    ownerId: 'user-organizer-15',
    title: 'Ghana Web3 & Crypto Developers Conference',
    description: 'Exploring smart contract development, decentralized finance protocols, and blockchain adoption across West Africa.',
    category: 'Technology',
    coverImage: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-10T09:30:00.000Z',
    endAt: '2026-11-10T17:30:00.000Z',
    venue: 'Accra International Conference Centre',
    address: 'Castle Road, Ridge',
    city: 'Accra',
    price: 'GHS 80',
    isFree: false,
    organizer: {
      name: 'Web3 Ghana Builders',
      logo: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1bd?w=200&auto=format&fit=crop&q=80',
      bio: 'Community of blockchain engineers, Smart Contract developers, and DeFi founders.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'evt-116',
    ownerId: 'user-organizer-16',
    title: 'Highlife & Afro-Jazz Heritage Night',
    description: 'Savor live acoustic Highlife guitar rhythms, brass sections, and smooth Afro-Jazz fusion performed by veteran and youth legends.',
    category: 'Music & Concerts',
    coverImage: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-10-30T19:30:00.000Z',
    endAt: '2026-10-30T23:30:00.000Z',
    venue: '+233 Jazz Bar & Grill',
    address: 'Ring Road Central',
    city: 'Accra',
    price: 'GHS 50',
    isFree: false,
    organizer: {
      name: '+233 Live Club',
      logo: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&auto=format&fit=crop&q=80',
      bio: 'Accra premier live music venue showcasing African jazz, highlife, and soul.',
      type: 'Company',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'evt-117',
    ownerId: 'user-organizer-17',
    title: 'West Africa E-Commerce & Logistics Expo',
    description: 'Learn latest strategies in cross-border payments, last-mile delivery tech, and inventory management for online merchants.',
    category: 'Business',
    coverImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-18T09:00:00.000Z',
    endAt: '2026-11-18T16:00:00.000Z',
    venue: 'Tema Community Centre Auditorium',
    address: 'Community 1, Main Road',
    city: 'Tema',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'TradeNext West Africa',
      logo: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200&auto=format&fit=crop&q=80',
      bio: 'Connecting logistics hubs, payment gateways, and retail entrepreneurs.',
      type: 'Company',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'evt-118',
    ownerId: 'user-organizer-18',
    title: 'University Health Fair & Blood Donation Rally',
    description: 'Free health screenings, eye tests, blood pressure checks, and voluntary blood donation drive organized by medical students.',
    category: 'Community',
    coverImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-10-21T08:30:00.000Z',
    endAt: '2026-10-21T15:30:00.000Z',
    venue: 'UG Legon Night Market Square',
    address: 'University of Ghana Campus',
    city: 'Legon',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'UG Medical Students Association',
      logo: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=200&auto=format&fit=crop&q=80',
      bio: 'Promoting community health outreach, medical screening, and blood donation.',
      type: 'Student group',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'evt-119',
    ownerId: 'user-organizer-19',
    title: 'Cape Coast Castle Cultural Heritage Tour',
    description: 'Guided historical walk through Cape Coast Castle dungeons, heritage talks, and traditional drumming performances by local youth.',
    category: 'Arts & Culture',
    coverImage: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-01T10:00:00.000Z',
    endAt: '2026-11-01T14:00:00.000Z',
    venue: 'Cape Coast Castle Courtyard',
    address: 'Victoria Road',
    city: 'Cape Coast',
    price: 'GHS 30',
    isFree: false,
    organizer: {
      name: 'Central Heritage Guild',
      logo: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=200&auto=format&fit=crop&q=80',
      bio: 'Preserving West African historical sites and organizing educational tours.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 9,
    updatedAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'evt-120',
    ownerId: 'user-organizer-20',
    title: 'Campus Afro-Amapiano Rave',
    description: 'High energy outdoor party featuring top campus DJs, laser light shows, body paint stations, and food trucks.',
    category: 'Parties & Nightlife',
    coverImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-10-23T21:00:00.000Z',
    endAt: '2026-10-24T04:00:00.000Z',
    venue: 'Sarbah Hall Main Lawn',
    address: 'University of Ghana Main Campus',
    city: 'Legon',
    price: 'GHS 25',
    isFree: false,
    organizer: {
      name: 'Legon Party Central',
      logo: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=200&auto=format&fit=crop&q=80',
      bio: 'Campus event planners specializing in student nightlife and music festivals.',
      type: 'Student group',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'evt-121',
    ownerId: 'user-organizer-21',
    title: 'Women in STEM & Tech Leadership Forum',
    description: 'Inspirational keynotes and mentorship circles connecting female software engineers, scientists, and founders across Ghana.',
    category: 'Education',
    coverImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-14T10:00:00.000Z',
    endAt: '2026-11-14T15:00:00.000Z',
    venue: 'Accra Digital Centre',
    address: 'Ring Road West',
    city: 'Accra',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'WomenTech Ghana',
      logo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
      bio: 'Empowering African women and girls with STEM education and tech leadership.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'evt-122',
    ownerId: 'user-organizer-22',
    title: 'Accra City 10K Charity Marathon',
    description: 'Lace up your running shoes! Run or walk along the coastal road to support local youth education initiatives.',
    category: 'Sports',
    coverImage: 'https://images.unsplash.com/photo-1530541930197-ff16ac917b0e?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-07T06:00:00.000Z',
    endAt: '2026-11-07T10:00:00.000Z',
    venue: 'Independence Square Park',
    address: 'Black Star Square',
    city: 'Accra',
    price: 'GHS 20',
    isFree: false,
    organizer: {
      name: 'Accra Runners Club',
      logo: 'https://images.unsplash.com/photo-1517649763962-0c6232662000?w=200&auto=format&fit=crop&q=80',
      bio: 'Promoting marathon running, fitness, and health across Greater Accra.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'evt-123',
    ownerId: 'user-organizer-23',
    title: 'Eco-Green Beach Cleanup & Recycling Fair',
    description: 'Join environmental advocates for a morning beach cleanup at Laboma Beach followed by upcycling workshops and eco-vendor stalls.',
    category: 'Community',
    coverImage: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-10-17T07:00:00.000Z',
    endAt: '2026-10-17T12:00:00.000Z',
    venue: 'Laboma Beach Park',
    address: 'Laboma Beach Road',
    city: 'Accra',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'Green Earth Ghana',
      logo: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=200&auto=format&fit=crop&q=80',
      bio: 'Youth-led NGO focused on ocean conservation, plastic recycling, and climate action.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'evt-124',
    ownerId: 'user-organizer-24',
    title: 'West African Real Estate Investment Summit',
    description: 'A premium gathering of property developers, architectural firms, mortgage banks, and private equity investors.',
    category: 'Business',
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-25T09:00:00.000Z',
    endAt: '2026-11-25T17:00:00.000Z',
    venue: 'Mövenpick Ambassador Hotel',
    address: 'Independence Avenue',
    city: 'Accra',
    price: 'GHS 200',
    isFree: false,
    organizer: {
      name: 'PropTech & Real Estate GH',
      logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=200&auto=format&fit=crop&q=80',
      bio: 'Leading real estate intelligence network and property summit organizers.',
      type: 'Company',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now() - 86400000 * 4,
  },
  {
    id: 'evt-125',
    ownerId: 'user-organizer-25',
    title: 'Ghana National Theatre Drama Special',
    description: 'Watch the theatrical stage performance of classic Ghanaian literature accompanied by live traditional orchestra.',
    category: 'Arts & Culture',
    coverImage: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-10-29T18:30:00.000Z',
    endAt: '2026-10-29T21:30:00.000Z',
    venue: 'National Theatre of Ghana',
    address: 'South Liberia Road, Victoriaborg',
    city: 'Accra',
    price: 'GHS 45',
    isFree: false,
    organizer: {
      name: 'National Drama Company',
      logo: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=200&auto=format&fit=crop&q=80',
      bio: 'Official resident theatrical company of the National Theatre.',
      type: 'Institution',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'evt-126',
    ownerId: 'user-organizer-26',
    title: 'DevFest West Africa Code & Cloud Summit',
    description: 'Community-led developer conference covering Google Cloud Platform, Flutter, Android, AI APIs, and DevOps architecture.',
    category: 'Technology',
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-28T08:30:00.000Z',
    endAt: '2026-11-28T17:00:00.000Z',
    venue: 'Legon Hall Complex Auditorium',
    address: 'University of Ghana Main Campus',
    city: 'Legon',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'Google Developer Group Accra',
      logo: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=200&auto=format&fit=crop&q=80',
      bio: 'Developer community exploring web development, cloud computing, and AI.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'evt-127',
    ownerId: 'user-organizer-27',
    title: 'Gospel Praise Jubilee & Choral Night',
    description: 'An evening of classical choral hymns, gospel choir harmonies, and live instrumental worship in Kumasi.',
    category: 'Religion',
    coverImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-06T18:00:00.000Z',
    endAt: '2026-11-06T22:00:00.000Z',
    venue: 'KNUST Royal Parade Grounds',
    address: 'KNUST Campus',
    city: 'Kumasi',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'Kumasi Youth Mass Choir',
      logo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=200&auto=format&fit=crop&q=80',
      bio: 'Inter-denominational gospel choral group promoting unity through praise.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'evt-128',
    ownerId: 'user-organizer-28',
    title: 'Campus E-Sports & Gaming Championship',
    description: 'Competitive tournaments in EA FC 26, Tekken, Mortal Kombat, and Valorant with live caster commentary and cash prize pool.',
    category: 'Sports',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-10-31T12:00:00.000Z',
    endAt: '2026-10-31T20:00:00.000Z',
    venue: 'UG Student Union Lounge',
    address: 'University of Ghana Main Campus',
    city: 'Legon',
    price: 'GHS 15',
    isFree: false,
    organizer: {
      name: 'Ghana Cyber Gamers Club',
      logo: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=200&auto=format&fit=crop&q=80',
      bio: 'Organizing competitive esports tournaments and gaming conventions across universities.',
      type: 'Student group',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'evt-129',
    ownerId: 'user-organizer-29',
    title: 'Startup Founders Breakfast & VC Pitch',
    description: 'An intimate morning coffee roundtable where pre-seed founders pitch to angel investors and get direct feedback on unit economics.',
    category: 'Business',
    coverImage: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-04T08:00:00.000Z',
    endAt: '2026-11-04T10:30:00.000Z',
    venue: 'Impact Hub Accra',
    address: 'F71/6 Otswe Street, Osu',
    city: 'Accra',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'Accra Founder Network',
      logo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&auto=format&fit=crop&q=80',
      bio: 'Peer networking group for tech founders, product managers, and early investors.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'evt-130',
    ownerId: 'user-organizer-30',
    title: 'Accra Street Food & Jollof Battle 2026',
    description: 'The ultimate culinary showdown! Taste Ghanaian Jollof, Suya kebabs, Kelewele, and local craft drinks while voting for the champion chef.',
    category: 'Community',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-14T12:00:00.000Z',
    endAt: '2026-11-14T20:00:00.000Z',
    venue: 'Efua Sutherland Children’s Park',
    address: 'Castle Road',
    city: 'Accra',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'Taste of Ghana Culinary Society',
      logo: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=200&auto=format&fit=crop&q=80',
      bio: 'Celebrating authentic West African gastronomy, street food, and culinary talent.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'evt-131',
    ownerId: 'user-organizer-31',
    title: 'Mind & Body Mental Health Symposium',
    description: 'Expert talks on managing stress, university burnout, mindfulness practices, and accessible mental health support systems.',
    category: 'Health & Wellness',
    coverImage: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-19T14:00:00.000Z',
    endAt: '2026-11-19T17:30:00.000Z',
    venue: 'UG Balme Library Seminar Room',
    address: 'University of Ghana Main Campus',
    city: 'Legon',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'Wellness Alliance Ghana',
      logo: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=200&auto=format&fit=crop&q=80',
      bio: 'Advocating for mental health awareness and wellness support in universities.',
      type: 'Community',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'evt-132',
    ownerId: 'user-organizer-32',
    title: 'Fashion Week Accra & Emerging Designers',
    description: 'A high-fashion runway showcase featuring eco-friendly African textiles, avant-garde couture, and street style accessories.',
    category: 'Arts & Culture',
    coverImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-21T17:00:00.000Z',
    endAt: '2026-11-21T22:00:00.000Z',
    venue: 'Mövenpick Grand Ballroom',
    address: 'Independence Avenue',
    city: 'Accra',
    price: 'GHS 120',
    isFree: false,
    organizer: {
      name: 'Accra Fashion Council',
      logo: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=200&auto=format&fit=crop&q=80',
      bio: 'Promoting contemporary African fashion design, sustainable textiles, and runway events.',
      type: 'Company',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 9,
    updatedAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'evt-133',
    ownerId: 'user-organizer-33',
    title: 'Remote Work & Freelancer Expo',
    description: 'Discover global remote jobs, international payment setups, co-working spaces, and portfolio presentation skills for African creatives.',
    category: 'Career',
    coverImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-11T11:00:00.000Z',
    endAt: '2026-11-11T16:00:00.000Z',
    venue: 'BaseCamp Initiative Hub',
    address: 'East Legon, Boundary Road',
    city: 'Accra',
    price: 'Free',
    isFree: true,
    organizer: {
      name: 'Remote Africa Network',
      logo: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=200&auto=format&fit=crop&q=80',
      bio: 'Connecting African talent with global remote employment opportunities.',
      type: 'Company',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'evt-134',
    ownerId: 'user-organizer-34',
    title: 'Silent Disco & Beach Party',
    description: 'Switch between 3 wireless headphone channels featuring DJ Afrobeats, Amapiano, and Old School Hip-Hop right on the ocean shoreline.',
    category: 'Parties & Nightlife',
    coverImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-11-07T20:00:00.000Z',
    endAt: '2026-11-08T03:00:00.000Z',
    venue: 'Kokrobitey Beach Club',
    address: 'Kokrobitey Coast',
    city: 'Accra',
    price: 'GHS 70',
    isFree: false,
    organizer: {
      name: 'Silent Wave Entertainment',
      logo: 'https://images.unsplash.com/photo-1571266028243-e4733b0f0bb1?w=200&auto=format&fit=crop&q=80',
      bio: 'Pioneers in silent headphone parties and beach rave experiences.',
      type: 'Company',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'evt-135',
    ownerId: 'user-organizer-35',
    title: 'University Alumni Gala & Fundraiser',
    description: 'An elegant black-tie evening reuniting alumni, featuring live orchestra, dinner, and fundraising for campus library expansion.',
    category: 'Community',
    coverImage: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1200&auto=format&fit=crop&q=80',
    startAt: '2026-12-05T18:30:00.000Z',
    endAt: '2026-12-05T23:00:00.000Z',
    venue: 'Great Hall Lawn, University of Ghana',
    address: 'Legon Campus',
    city: 'Legon',
    price: 'GHS 180',
    isFree: false,
    organizer: {
      name: 'UG Alumni Secretariat',
      logo: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=200&auto=format&fit=crop&q=80',
      bio: 'Connecting alumni worldwide and supporting university development projects.',
      type: 'Institution',
    },
    status: 'published',
    createdAt: Date.now() - 86400000 * 14,
    updatedAt: Date.now() - 86400000 * 5,
  },'''

# 2. Additional 4 Vendors
extra_vendors = '''  {
    id: 'ven-113',
    ownerId: 'user-vendor-13',
    name: 'Royal Stage & Trussing Solutions',
    logo: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&auto=format&fit=crop&q=80',
    description: 'Heavy duty aluminium stage trusses, LED screens, hydraulic outdoor stages, and ground support systems for major festivals.',
    categories: ['Equipment Rental', 'Sound'],
    services: [
      { title: 'Concert Hydraulic Stage Rental', priceRange: 'GHS 4,500', description: 'Full 10x8m outdoor elevated stage structure with roof.' }
    ],
    location: 'KNUST Road',
    city: 'Kumasi',
    serviceArea: 'Ashanti & Northern Region',
    contact: { phone: '+233 24 999 0011', whatsapp: '+233249990011' },
    portfolio: ['https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop&q=80'],
    verified: true,
    status: 'published',
    createdAt: Date.now() - 86400000 * 14,
  },
  {
    id: 'ven-114',
    ownerId: 'user-vendor-14',
    name: 'Apex Security & VIP Guard Protocol',
    logo: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&auto=format&fit=crop&q=80',
    description: 'Crowd control officers, VIP personal bodyguards, metal detectors, and event entry access control team.',
    categories: ['Security'],
    services: [
      { title: 'Event Entry Guard Team (4 Guards)', priceRange: 'GHS 1,200', description: 'Professional entry screening, wristband checks, and crowd management.' }
    ],
    location: 'East Legon',
    city: 'Accra',
    serviceArea: 'Nationwide',
    contact: { phone: '+233 20 888 3344', whatsapp: '+233208883344' },
    portfolio: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80'],
    verified: true,
    status: 'published',
    createdAt: Date.now() - 86400000 * 10,
  },
  {
    id: 'ven-115',
    ownerId: 'user-vendor-15',
    name: 'Focal Point Drone & Cinematic Video',
    logo: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=400&auto=format&fit=crop&q=80',
    description: 'Licensed 4K drone aerial videography, 360-degree event photo booths, and cinematic festival documentary films.',
    categories: ['Videography', 'Photography'],
    services: [
      { title: 'Aerial Drone Video Coverage (Full Day)', priceRange: 'GHS 1,800', description: '4K aerial shots, licensed pilot, color graded raw footage.' }
    ],
    location: 'Airport Residential',
    city: 'Accra',
    serviceArea: 'Accra & Tema',
    contact: { phone: '+233 55 777 2211', whatsapp: '+233557772211' },
    portfolio: ['https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&auto=format&fit=crop&q=80'],
    verified: true,
    status: 'published',
    createdAt: Date.now() - 86400000 * 7,
  },
  {
    id: 'ven-116',
    ownerId: 'user-vendor-16',
    name: 'Golden Touch Ushers & VIP Hospitality',
    logo: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&auto=format&fit=crop&q=80',
    description: 'Experienced ushering squad for academic graduations, weddings, corporate launches, and sports tournaments.',
    categories: ['Ushers'],
    services: [
      { title: 'Ushering Squad (5 Protocol Ushers)', priceRange: 'GHS 750', description: 'Guest registration, seating guidance, and program distribution.' }
    ],
    location: 'Cape Coast Central',
    city: 'Cape Coast',
    serviceArea: 'Central & Western Region',
    contact: { phone: '+233 24 444 8899', whatsapp: '+233244448899' },
    portfolio: ['https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&auto=format&fit=crop&q=80'],
    verified: true,
    status: 'published',
    createdAt: Date.now() - 86400000 * 12,
  },'''

# Insert extra_events before line ending of INITIAL_EVENTS
content = content.replace("    status: 'published',\n    createdAt: Date.now() - 86400000 * 10,\n    updatedAt: Date.now() - 86400000 * 4,\n  },\n];", "    status: 'published',\n    createdAt: Date.now() - 86400000 * 10,\n    updatedAt: Date.now() - 86400000 * 4,\n  },\n" + extra_events + "\n];")

# Insert extra_vendors before line ending of INITIAL_VENDORS
content = content.replace("    verified: true,\n    status: 'published',\n    createdAt: Date.now() - 86400000 * 6,\n  },\n];", "    verified: true,\n    status: 'published',\n    createdAt: Date.now() - 86400000 * 6,\n  },\n" + extra_vendors + "\n];")

# Update localStorage merge logic so missing seed items are added automatically
old_merge_code = """      const storedEvts = localStorage.getItem(STORAGE_EVENTS);
      if (storedEvts) {
        const parsed: EventModel[] = JSON.parse(storedEvts);
        const merged = parsed.map((evt) => {
          const init = INITIAL_EVENTS.find((i) => i.id === evt.id);
          if (init) {
            return {
              ...init,
              ...evt,
              lineup: evt.lineup || init.lineup,
              agenda: evt.agenda || init.agenda,
              whatToExpect: evt.whatToExpect || init.whatToExpect,
              whoShouldAttend: evt.whoShouldAttend || init.whoShouldAttend,
              pastEditions: evt.pastEditions || init.pastEditions,
            };
          }
          return evt;
        });
        setEvents(merged);
      } else {
        setEvents(INITIAL_EVENTS);
      }

      const storedVends = localStorage.getItem(STORAGE_VENDORS);
      setVendors(storedVends ? JSON.parse(storedVends) : INITIAL_VENDORS);"""

new_merge_code = """      const storedEvts = localStorage.getItem(STORAGE_EVENTS);
      if (storedEvts) {
        const parsed: EventModel[] = JSON.parse(storedEvts);
        const merged = parsed.map((evt) => {
          const init = INITIAL_EVENTS.find((i) => i.id === evt.id);
          if (init) {
            return {
              ...init,
              ...evt,
              lineup: evt.lineup || init.lineup,
              agenda: evt.agenda || init.agenda,
              whatToExpect: evt.whatToExpect || init.whatToExpect,
              whoShouldAttend: evt.whoShouldAttend || init.whoShouldAttend,
              pastEditions: evt.pastEditions || init.pastEditions,
            };
          }
          return evt;
        });
        // Add any new initial seed events missing from stored list
        INITIAL_EVENTS.forEach((init) => {
          if (!merged.some((m) => m.id === init.id)) {
            merged.push(init);
          }
        });
        setEvents(merged);
      } else {
        setEvents(INITIAL_EVENTS);
      }

      const storedVends = localStorage.getItem(STORAGE_VENDORS);
      if (storedVends) {
        const parsedVends: VendorProfileModel[] = JSON.parse(storedVends);
        INITIAL_VENDORS.forEach((initV) => {
          if (!parsedVends.some((pv) => pv.id === initV.id)) {
            parsedVends.push(initV);
          }
        });
        setVendors(parsedVends);
      } else {
        setVendors(INITIAL_VENDORS);
      }"""

content = content.replace(old_merge_code, new_merge_code)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Successfully updated EventStore.tsx with 35 events and 16 vendors.")
